---
title: "Employment as a determinant of gender-based violence: the Ecuadorian case"
author: 
  - name: "Ingrid O."
  - name: "Jhanelly Ch."
  - name: "Karen O."
  - name: "Odalis Cl."
  - name: "Alan D."
format: pdf
number-sections: true
bibliography: refs.bib
margin: 1
---

**GitHub repository**: [https://github.com/OdalisClemente/Stadistica_Rstudio](https://github.com/OdalisClemente/Stadistica_Rstudio) 

# Introduction
Violence against women is an issue that raises alarms in society, as it manifests itself in different ways and in different spaces. In Ecuador alone, during 2023, 277 women were victims of femicide, while the Gender Table of International Cooperation (MEGECI, 2023) reported that in 2019, 5,785,295 women were victims of some type of violence. These figures are alarming and encourage the search for the causes of this type of violence, in order to implement measures that contribute to its eradication.

In an attempt to explain these causes, the relationship that may exist between employment and violence against women has been discussed, interpreting it as a complex cause that is influenced by cultural, psychological and social factors, since women victims of violence lack a safe environment that supports their access to employment and their work performance; in addition, employment can become an empowering factor for women, allowing them to overcome difficult personal situations and even break the cycle of violence (Sklavou et al., 2020).

Following this same line, a study focused on the analysis of microdata from 35 countries located in different regions of Africa, Asia and Latin America, was able to establish that employment in women can be associated with an increase in violence by their partners, considering that it has a significant negative effect on domestic violence.  mainly in Latin America and East Africa (Khan & Klasen, 2018).

It is important to note that, in the study of the relationship between employment and violence against women, there are two positions: the first, in which it is pointed out that a better economic status in women reduces violence and, the second, in which it is suggested that employment produces a reaction effect in which an increase in female empowerment can provoke violent reactions on the part of men (Bhalotra et al., 2021)

With this background, the following research question arises: Is there a significant difference in the percentage of people who have suffered violence between those who have never worked and those who have been employed?

It is important to inquire about this, since although there are alarming figures and statistical data, contextualizing the specific situation of Ecuador will allow us to establish whether employment reduces violence or increases it, since although there is research on the effects of employment on social and emotional well-being, few studies have focused on analyzing whether there is a significant difference in victimization between these two groups. In addition, understanding these patterns can provide relevant data for social organizations and public policies in the reduction of violence.

# Data
## Data source
The data for this study is based on the Encuesta Nacional sobre Relaciones Familiares y Violencia de Género contra las Mujeres (ENVIGMU), a nationally representative survey conducted in 2019 by the Instituto Nacional de Estadísticas y Censos (INEC). This survey collects comprehensive data on violence against women in different spheres of life, including physical, psychological, sexual, and economic violence. The target population includes women aged 15 and older, and the data covers both lifetime experiences and those within the last 12 months.

## Variables considered
The main variables for this study are:

- Dependent variable (experience of violence): this is categorized based on whether respondents have ever experienced physical, psychological, or sexual violence. The types of violence are reported across different settings, such as the workplace, family, and social environments.

- Independent variable (work history): this variable divides respondents into two groups.

    - Women who have never worked.

    - Women who have worked at some point in their lives.

Additionally, the data allows for the analysis of other demographic control variables, such as age, education level, ethnicity, and geographic location, which can influence both the likelihood of being employed and the experience of violence.

# Data usage 
In this study, the data will be used to compare the percentage of women who have experienced violence between two groups: those who have never worked and those who have been employed. The analysis will involve the presentation of percentages for each group, showing the prevalence of violence in both categories.

To determine whether there is a statistically significant difference between these two groups, hypothesis testing will be conducted. The hypothesis tests will assess whether the observed differences in violence rates are significant or could have occurred by chance. This method ensures that any identified disparities between the groups are robust and supported by statistical evidence.

Additionally, the study will control for factors such as age, education, and geographic location, which could influence both employment status and experiences of violence. The results will provide a clear comparison, highlighting whether having worked or not is associated with a higher likelihood of experiencing violence.


# Methods
## Participants
The present study focused on women aged 15 and older who answered questions assessing violence against women, in order to determine whether there is a difference between the proportion of women who work and those who do not work, related to whether they have suffered some form of domestic violence.

## Study size and missing data
In this study, the initial sample consisted of 19,161 women aged 15 years or older from 24 provinces in mainland Ecuador, including data from the Amazonian and Galapagos provinces. From the set of variables used to assess differences in the proportion of women who are employed or not and whether they have experienced any form of domestic violence, missing values were removed due to participants selecting "I don’t know or don’t remember" as a response.

## Stadistical methods
To evaluate the results of this research, various hypothesis testing methods were applied as a fundamental statistical approach to facilitate decision-making regarding the validity of specific claims about a population based on sample data. The hypothesis testing process involved formulating two opposing propositions:

- **Null Hypothesis ($H_0$):** This is a statement asserting that there is no significant difference or effect between the analyzed groups or variables. Any observed difference is attributed to chance or sample variations. Simply put, the null hypothesis proposes that there is no meaningful change or relationship within the context of the study. It is set up to be either refuted or accepted based on the data obtained. As stated by @crossref_crossref_nodate, "the null hypothesis asserts that there is no difference or that the effect is zero."

- **Alternative Hypothesis ($H_1$):** This is the statement opposing the null hypothesis, asserting that there is a significant difference or effect in the analyzed variables. The alternative hypothesis is accepted if the data provides sufficient evidence against the null hypothesis. According to @holland_statistics_1986, "the alternative hypothesis reflects the existence of a significant effect or difference in the study."

For this analysis, the proportion test was used, a statistical tool designed to compare observed proportions between groups within the sample. This approach is particularly useful for assessing whether observed differences between proportions of significant categories are statistically relevant. In this study, variables were created to record the total number of married women in two conditions: those who work and have experienced violence, and those who do not work but have also experienced violence.

This approach is essential for determining whether the observed differences have statistical significance or are due to chance, thereby strengthening the interpretation of the results.

In this study, two variables were created to store the total number of women who work and the total number of women who do not work in the sample. Additionally, two more variables were created to record the total number of women who work and have experienced violence, as well as a separate set for women who do not work and have experienced violence.

# Results
With the created variables containing the total values from the selected sample, proportion tests were performed to compare the differences between women who work or do not work and whether they have experienced violence or not. The results of the hypothesis tests are described below:

## First Proportions Test

**Hypothesis testing:**

- $H_0$: The proportion of married women who have experienced violence is the same between those who work and those who do not work.

- $H_1$: The proportion of married women who have experienced violence differs between those who work and those who do not work.

**Statistical test result:**

| Parámetro                  | Valor       |
|----------------------------|-------------|
| X-squared                   | _36.045_      |
| Grados de libertad (df)     | _1_           |
| Valor p (p-value)           | _1.928e-09_   |
| Hipótesis alternativa       | _two.sided_  |
| Intervalo de confianza (95%)| _0.03905297_ - _0.07709635_ |
| Prop. mujeres que trabajan  | _0.4491349_  |
| Prop. mujeres que no trabajan| _0.3910603_  |

The test indicates statistically significant evidence to reject $H_0$, suggesting a notable difference between married women who have experienced violence and work compared to those who do not work.

## Second Proportions Test

**Hypothesis testing:**

- $H_0$: There is no difference in the proportion of married women who have experienced violence between those who work and those who do not work.

- $H_1$: The proportion of married women who have experienced violence and are employed is greater than that of women who are not employed.

**Statistical test result:**

| Parámetro                  | Valor       |
|----------------------------|-------------|
| X-squared                   | _36.045_      |
| Grados de libertad (df)     | _1_           |
| Valor p (p-value)           | _9.64e-10_    |
| Hipótesis alternativa       | _greater_       |
| Intervalo de confianza (95%)| _0.04208053_ - _1.00000000_ |
| Prop. mujeres que trabajan  | _0.4491349_   |
| Prop. mujeres que no trabajan| _0.3910603_  |

The significant p-value provides sufficient evidence to reject $H_0$, indicating that the proportion of married women who have experienced violence and are employed is higher than that of those who are not employed.

## Third Proportions Test

**Hypothesis testing:**

- $H_0$: There is no difference in the proportion of women who believe that the abuse was due to jealousy compared to those who do not.



- $H_1$: There is a difference in the proportion of women who believe that the abuse was due to jealousy compared to those who do not.

**Statistical test result:**

| Parámetro                  | Valor       |
|----------------------------|-------------|
| X-squared                   | _59.842_      |
| Grados de libertad (df)     | _1_           |
| Valor p (p-value)           | _1.028e-14_   |
| Hipótesis alternativa       | _greater_       |
| Intervalo de confianza (95%)| _-0.10284102 - _-0.06110805_ |
| Prop. mujeres que trabajan  | _0.4587894_     |
| Prop. mujeres que no trabajan| _0.5407639_    |

The results do not show sufficient statistical evidence to reject $H_0$, so no significant difference is observed in the proportion of women who believe that the abuse was due to jealousy compared to those who do not.

## Fourth Proportions Test

**Statistical test result:**

- $H_0$: There is no difference in the proportion of women who believe that abuse was due to jealousy compared to those who do not believe so.

- $H_1$: LThe proportion of women who believe that abuse was due to jealousy is greater than those who do not believe so.

**Statistical test result:**

| Parámetro                  | Valor       |
|----------------------------|-------------|
| X-squared                   | _59.842_      |
| Grados de libertad (df)     | _1_           |
| Valor p (p-value)           | _1.028e-14_   |
| Hipótesis alternativa       | _greater_       |
| Intervalo de confianza (95%)| _-0.09952215_ - _1.00000000_ |
| Prop. mujeres que trabajan  | _0.4587894_      |
| Prop. mujeres que no trabajan| _0.5407639_     |

With a non-significant p-value, we do not reject $H_0$, indicating that there is no difference in the proportion of women who believe that abuse was caused by jealousy compared to those who do not believe it.

# Discussion

The results of this research provide a detailed understanding of the relationship between the employment status of married women and their experience of violence. Through hypothesis testing, a significant trend was observed: women who work report a higher proportion of violence compared to those who do not work. This finding is relevant as it suggests a possible interaction between employment and exposure to violence, potentially linked to factors such as economic dependence and power dynamics within relationships. Literature suggests that, in certain contexts, employment can empower women, providing them with greater resources to confront or leave situations of violence. However, in other cases, employment may also intensify conflicts within the home, particularly if it is perceived as a threat to the authority or control of the abuser.

Additionally, the confidence intervals and p-values across all tests provide robust statistical evidence to support the validity of the findings, demonstrating that the observed differences are not due to chance. This not only reinforces the importance of employment as a key factor in analyzing gender-based violence but also calls for a careful interpretation of emotional factors, such as jealousy, within the dynamics of violence.

# Conclusion

The findings of this study offer a comprehensive perspective on how the employment status of married women influences their experiences of violence, highlighting significant differences between those who work and those who do not. These results suggest that employment may play both a protective and a conflictual role in women’s lives, depending on contextual and cultural factors that shape relationship dynamics and family interactions. The higher proportion of working women experiencing violence may reflect a combination of factors, including the economic independence some women achieve through employment, which could be perceived as a threat in contexts characterized by control or dependency in relationships.

Nonetheless, the results do not provide sufficient evidence to conclude that jealousy is a distinct motive for abuse, underscoring the need to explore other factors that may influence the perception and experience of domestic violence. This suggests the importance of analyzing additional external factors that could introduce causality within the investigation.

# Reference